name: todo-app
region: tor
services:
  - name: web
    source_dir: /
    github:
      repo: your-username/todo-app
      branch: main
    run_command: npm start
    build_command: npm run build
    environment_slug: node-js
    instance_count: 2
    instance_size_slug: basic-xxs
    envs:
      - key: MONGODB_URI
        value: ${db.DATABASE_URL}
        scope: RUN_TIME
      - key: NODE_ENV
        value: production
        scope: RUN_TIME

databases:
  - name: db
    engine: MONGODB
    version: "7.0"
    production: false

